// File: fpga_pins_on.v
// Generated by MyHDL 0.11.49
// Date: Wed Oct 23 10:14:17 2024


`timescale 1ns/10ps

module fpga_pins_on (
    led0,
    led1,
    led2,
    led3,
    led4,
    led5,
    led6,
    led7,
    led8,
    led9,
    led10,
    led11,
    led12,
    led13,
    led14,
    led15
);


output led0;
reg led0;
output led1;
reg led1;
output led2;
reg led2;
output led3;
reg led3;
output led4;
reg led4;
output led5;
reg led5;
output led6;
reg led6;
output led7;
reg led7;
output led8;
reg led8;
output led9;
reg led9;
output led10;
reg led10;
output led11;
reg led11;
output led12;
reg led12;
output led13;
reg led13;
output led14;
reg led14;
output led15;
reg led15;




initial begin: FPGA_PINS_ON_LOGIC
    led0 <= 1;
    led1 <= 1;
    led2 <= 1;
    led3 <= 1;
    led4 <= 1;
    led5 <= 1;
    led6 <= 1;
    led7 <= 1;
    led8 <= 1;
    led9 <= 1;
    led10 <= 1;
    led11 <= 1;
    led12 <= 1;
    led13 <= 1;
    led14 <= 1;
    led15 <= 1;
    # 10;
end

endmodule
